### ISSUE TITLE
velocyto.R

### ISSUE THREAD

**Issue by byeongchangsim** [xizhihui/pipelines#1]
Hello

I have a question with velocyto.R, but I don't know your email, so I'm leaving an inquiry here.

In the process of installing velocyto, there is an error saying that boost_filesystem and boost_system cannot be found. I wonder if there is a solution.

The error message is as follows.

D:/Rtools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lboost_filesystem
D:/Rtools/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lboost_system

I built boost on windows and made it run up to the d2.exe file.

thank you.
@xizhihui

**Comment by xizhihui** [comment]
sorry, I did not use velocyto for long time. 
For this boost_system bug, please refer to #https://github.com/velocyto-team/velocyto.R/issues/141
good luck~~
